### PR TITLE
Add/Edit Headers

### PR DESCRIPTION
**Pull request by jellison**
CRUD headers. Added FontAwesome via react-specific package.

### CODE REVIEW

**Comment by smithej** [comment]
This looks pretty good. I was at first off put because there was no label above the header or value input form columns. However the values in the respective columns should give enough context as to what the intended content would be.

**Comment by smithej** [comment]
Looks like there is a small issue when you delete all the header/value rows and then try to add one. It isn't reliably reproducible though. I usually have to create a handful and then add a handful and repeat this until it happens.

Screenshot from 2019-09-03 19-15-40

**Comment by jellison** [comment]
@smithej Good catch! Wasn't removing the `ref` from the `nodes` collection on delete. I cleaned up the `ref` tracking while I was at it. Should be fixed now.

**Comment by smithej** [comment]
Those changes look good, I no longer can reproduce that bug but I think I found another one. I don't know if it's specific to this PR though.

This is assuming you're using the putter-data.zip you posted in the slack channel. But the app should open on request 1. Navigate to request 2 and then click on the headers tab. Then click on request 1 again. I am observing the app crashing with the following errors.

Screenshot from 2019-09-07 14-45-47

**Comment by smithej** [comment]
I can't reproduce the latest issue with the original PR so it looks like [6b4e3c1](https://github.com/putter-app/putter/pull/9/commits/6b4e3c1ef36cf6aeaa9376660f51437c96c0b6e2) introduced a regression.

**Comment by smithej** [comment]
The latest commit resolved the issue I was seeing. This looks good to me.

**Pull request merged**
